"""empty message

Revision ID: 3553325d359b
Revises: 56be9bc8b505
Create Date: 2023-10-28 12:58:17.760449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '3553325d359b'
down_revision: Union[str, None] = '56be9bc8b505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scans', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.create_unique_constraint(None, 'scans', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='unique')
    op.drop_column('scans', 'created_at')
    # ### end Alembic commands ###
