"""empty message

Revision ID: 56be9bc8b505
Revises: 55d0e157d588
Create Date: 2023-10-28 12:23:57.559391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '56be9bc8b505'
down_revision: Union[str, None] = '55d0e157d588'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('object_profile_id', sa.Integer(), nullable=False),
    sa.Column('subject_profile_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_profile_id'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['subject_profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    # ### end Alembic commands ###
