"""empty message

Revision ID: a2340884a7c7
Revises: 9b1e5aafe63f
Create Date: 2023-10-28 01:07:15.757498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = 'a2340884a7c7'
down_revision: Union[str, None] = '9b1e5aafe63f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'institution_types', ['id'])
    op.create_unique_constraint(None, 'institutions', ['id'])
    op.create_unique_constraint(None, 'profiles', ['id'])
    op.add_column('profiles_to_institutions', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'profiles_to_institutions', ['id'])
    op.create_foreign_key(None, 'profiles_to_institutions', 'profiles', ['profile_id'], ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'profiles_to_institutions', type_='foreignkey')
    op.drop_constraint(None, 'profiles_to_institutions', type_='unique')
    op.drop_column('profiles_to_institutions', 'profile_id')
    op.drop_constraint(None, 'profiles', type_='unique')
    op.drop_constraint(None, 'institutions', type_='unique')
    op.drop_constraint(None, 'institution_types', type_='unique')
    # ### end Alembic commands ###
